networks:
  pgnet:
    driver: bridge

services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - pgnet
    healthcheck:
      test: [ "CMD-SHELL", "etcdctl --cluster=true endpoint health || exit 1" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s
  pg1: &pg_base
    container_name: pg1
    build:
      context: .
    environment:
      - PATRONI_NAME=pg1
    volumes:
      - ./patroni.yml:/etc/patroni/patroni.yml:ro
    networks:
      - pgnet
    depends_on:
      - etcd
  pg2:
    <<: *pg_base
    container_name: pg2
    environment:
      - PATRONI_NAME=pg2
  pg3:
    <<: *pg_base
    container_name: pg3
    environment:
      - PATRONI_NAME=pg3
